#!/bin/sh
#
# chkconfig: - 91 35
#
jws_path=/jws.mono/jexus
case "$1" in
	start)
		echo "Start Jexus Web Server..."
		$jws_path/jws start
		;;
	stop)
		echo "Stop Jexus Web Server..."
		$jws_path/jws stop
		;;
	restart)
		echo "Restart Jexus Web Server..."
		$jws_path/jws restart
		;;
	status)
		$jws_path/jws status
		;;
	version|-v)
		$jws_path/jws -v
		;;
	*)
		echo 'oh no!!!'
		exit 1
		;;
esac
exit 0

